### ISSUE TITLE
support media type

### ISSUE THREAD

**Issue by xiaoweihong** [EtixLabs/RTSPAllTheThings#45]
you project is very powerful.But I want to know your project can suport how many type of media?avi,mp4,h264,h265......
thank you.

**Comment by Ullaakut** [comment]
Hi @xiaoweihong ! Thanks for the kind words.

Since we use playbin as the pipeline's entrypoint, we support:

### Container types

* mp4
* asf
* avi
* mpeg
* ogg
* wav

### Encoding formats

* 3ivx
* DivX
* dv | Digital Video
* ffv | FFMpeg video
* h263 | H-263 video
* h264 | H-264 video
* huffyuv | Huffyuv video
* indeo | Indeo video
* jpeg | Motion-JPEG video
* mpeg | MPEG video
* msmpeg | Microsoft MPEG-4 video deviations
* wmv | Windows Media Video
* xvid | XviD video

Some other formats and containers should be compatible as well, however it's not 100% certain. See [this link](https://gstreamer.freedesktop.org/documentation/plugin-development/advanced/media-types.html) for more information :)
